[project]
name = "voice-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "vosk",
    "pyttsx3",
    "wikipedia",
    "pyjokes",
    "tts",
    "torch",
    "transformers",
    "pyaudio",
]
